//! Contains all the return types from the Riot Api.

mod error;
mod game_result;
mod highest_achieved_season_tier;
mod lane;
mod league_entry;
mod league_item;
mod league_list;
mod mastery;
mod r#match;
mod match_list;
mod match_reference;
mod mini_series;
mod participant;
mod participant_identity;
mod participant_stats;
mod participant_timeline;
mod player;
mod role;
mod rune;
mod summoner;
mod team;
mod team_bands;
mod team_stats;

pub use error::Error;
pub use game_result::GameResult;
pub use highest_achieved_season_tier::HighestAchievedSeasonTier;
pub use lane::Lane;
pub use league_entry::LeagueEntry;
pub use league_item::LeagueItem;
pub use league_list::LeagueList;
pub use mastery::Mastery;
pub use match_list::MatchList;
pub use match_reference::MatchReference;
pub use mini_series::MiniSeries;
pub use participant::Participant;
pub use participant_identity::ParticipantIdentity;
pub use participant_stats::ParticipantStats;
pub use participant_timeline::ParticipantTimeline;
pub use player::Player;
pub use r#match::Match;
pub use role::Role;
pub use rune::Rune;
pub use summoner::Summoner;
pub use team::Team;
pub use team_bands::TeamBands;
pub use team_stats::TeamStats;
